version: '3'
services:
  redis:
    image: redis:6.2
    container_name: redis
    command: redis-server /etc/redis.conf #连接容器时需要设置密码，启动的时候按照配置文件启动
    ports:
      - "6379:6379"  #设置端口
    volumes: #映射配置文件路径，数据路径
      - "/usr/local/soft/redis/redis.conf:/etc/redis.conf"
      #- "/usr/local/soft/redis/data:/data"
    restart: always #设置始终重启
    networks:
      - nginx_network

networks:
  nginx_network:
    external: true
